# Form implementation generated from reading ui file 'src/ExpenseTableWithButtons.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ExpenseTableWithButtons(object):
    def setupUi(self, ExpenseTableWithButtons):
        ExpenseTableWithButtons.setObjectName("ExpenseTableWithButtons")
        ExpenseTableWithButtons.resize(413, 289)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ExpenseTableWithButtons.sizePolicy().hasHeightForWidth())
        ExpenseTableWithButtons.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(ExpenseTableWithButtons)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.expense_table = QtWidgets.QTableWidget(parent=ExpenseTableWithButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expense_table.sizePolicy().hasHeightForWidth())
        self.expense_table.setSizePolicy(sizePolicy)
        self.expense_table.setObjectName("expense_table")
        self.expense_table.setColumnCount(0)
        self.expense_table.setRowCount(0)
        self.verticalLayout_2.addWidget(self.expense_table)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(-1, 6, -1, 6)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.expense_new = QtWidgets.QToolButton(parent=ExpenseTableWithButtons)
        self.expense_new.setObjectName("expense_new")
        self.horizontalLayout_2.addWidget(self.expense_new)
        self.expense_remove = QtWidgets.QToolButton(parent=ExpenseTableWithButtons)
        self.expense_remove.setObjectName("expense_remove")
        self.horizontalLayout_2.addWidget(self.expense_remove)
        self.expense_edit = QtWidgets.QToolButton(parent=ExpenseTableWithButtons)
        self.expense_edit.setObjectName("expense_edit")
        self.horizontalLayout_2.addWidget(self.expense_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(ExpenseTableWithButtons)
        QtCore.QMetaObject.connectSlotsByName(ExpenseTableWithButtons)

    def retranslateUi(self, ExpenseTableWithButtons):
        _translate = QtCore.QCoreApplication.translate
        ExpenseTableWithButtons.setWindowTitle(_translate("ExpenseTableWithButtons", "Form"))
        self.expense_new.setText(_translate("ExpenseTableWithButtons", "New"))
        self.expense_remove.setText(_translate("ExpenseTableWithButtons", "Remove"))
        self.expense_edit.setText(_translate("ExpenseTableWithButtons", "Edit"))
