# Form implementation generated from reading ui file 'src/EditFinancial.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditFinancial(object):
    def setupUi(self, EditFinancial):
        EditFinancial.setObjectName("EditFinancial")
        EditFinancial.resize(326, 123)
        self.layoutWidget = QtWidgets.QWidget(parent=EditFinancial)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 321, 118))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.name = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.name.setObjectName("name")
        self.horizontalLayout.addWidget(self.name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.amount = QtWidgets.QSpinBox(parent=self.layoutWidget)
        self.amount.setObjectName("amount")
        self.horizontalLayout_2.addWidget(self.amount)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.category = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.category.setEditable(True)
        self.category.setObjectName("category")
        self.horizontalLayout_3.addWidget(self.category)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.frequency = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.frequency.setObjectName("frequency")
        self.horizontalLayout_4.addWidget(self.frequency)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.layoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_5.addWidget(self.buttonBox)

        self.retranslateUi(EditFinancial)
        self.buttonBox.rejected.connect(EditFinancial.reject) # type: ignore
        self.buttonBox.accepted.connect(EditFinancial.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(EditFinancial)

    def retranslateUi(self, EditFinancial):
        _translate = QtCore.QCoreApplication.translate
        EditFinancial.setWindowTitle(_translate("EditFinancial", "Dialog"))
        self.label.setText(_translate("EditFinancial", "Name:"))
        self.label_2.setText(_translate("EditFinancial", "Amount:"))
        self.label_3.setText(_translate("EditFinancial", "Category:"))
        self.label_4.setText(_translate("EditFinancial", "Frequency:"))
